dist: xenial
os: linux
language: node_js

node_js:
- '12'
- '14'
- '16'

jobs:
  include:
  - node_js: '12'
    env: BROWSER_NAME=chrome BROWSER_VERSION=latest
  - node_js: '12'
    env: BROWSER_NAME=chrome BROWSER_VERSION=29
  - node_js: '12'
    env: BROWSER_NAME=firefox BROWSER_VERSION=latest
  - node_js: '12'
    env: BROWSER_NAME=opera BROWSER_VERSION=latest
  - node_js: '12'
    env: BROWSER_NAME=safari BROWSER_VERSION=latest
  - node_js: '12'
    env: BROWSER_NAME=safari BROWSER_VERSION=7
  - node_js: '12'
    env: BROWSER_NAME=safari BROWSER_VERSION=6
  - node_js: '12'
    env: BROWSER_NAME=safari BROWSER_VERSION=5
  - node_js: '12'
    env: BROWSER_NAME=ie BROWSER_VERSION=11
  - node_js: '12'
    env: BROWSER_NAME=ie BROWSER_VERSION=10
  - node_js: '12'
    env: BROWSER_NAME=ie BROWSER_VERSION=9